apiVersion: v1
kind: ServiceAccount
metadata:
  name: quickstart-app
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: quickstart-app
  name: quickstart-app
  namespace: quickstart-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quickstart-app
  template:
    metadata:
      labels:
        app: quickstart-app
      annotations:
        conjur.org/authn-identity: host/conjur/authn-k8s/quickstart-cluster/apps/quickstart-app
        conjur.org/container-mode: init
        conjur.org/secrets-destination: file
        conjur.org/conjur-secrets.test-app: |
          - quickstart-app-resources/url
          - quickstart-app-resources/admin_username: username
          - quickstart-app-resources/admin_password: password
        conjur.org/secret-file-path.test-app: "./credentials.json"
        conjur.org/secret-file-format.test-app: "json"
    spec:
      serviceAccountName: quickstart-app
      containers:
      - name: file-examiner
        image: ubuntu:latest
        command: [ "/bin/bash", "-c", "--" ]
        args: [ "while true; do sleep 10; done;" ]
        volumeMounts:
          - name: conjur-secrets
            mountPath: /opt/secrets/conjur
            readOnly: true
      initContainers:
      - name: cyberark-secrets-provider-for-k8s
        image: 'cyberark/secrets-provider-for-k8s:latest'
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: conjur-connect
        volumeMounts:
          - name: podinfo
            mountPath: /conjur/podinfo
          - name: conjur-secrets
            mountPath: /conjur/secrets
          - name: conjur-templates
            mountPath: /conjur/templates
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: conjur-secrets
          emptyDir:
            medium: Memory
        - name: conjur-templates
          emptyDir:
            medium: Memory
